#!/bin/sh

WORKDIR=$(pwd)

gosu ${UID}:${GID} sh -c "export GOROOT=/usr/local/go \
&& export PATH=${PATH}:${GOROOT}/bin \
&& export GOPATH=${WORKDIR} \
&& export GOBIN=${GOPATH}/bin \
&& cd ${WORKDIR} \
&& /usr/local/go/bin/go ${@}"
