#!/bin/sh

WORKDIR=/usr/app/src

export GOROOT=/usr/local/go
export PATH=${PATH}:${GOROOT}/bin
export GOPATH=${WORKDIR}
export GOBIN=${GOPATH}/bin

if [ '$@' == '' ]; then
    exec su-exec ${UID}:${GID} tini -- /usr/local/go/bin/go version
else
    exec su-exec ${UID}:${GID} tini -- /usr/local/go/bin/go "$@"
fi

