#!/bin/sh

WORKDIR=$(pwd)

export GOROOT=/usr/local/go
export PATH=${PATH}:${GOROOT}/bin
export GOPATH=${WORKDIR}
export GOBIN=${GOPATH}/bin

chown ${UID}:${GID} ${WORKDIR}
if [ '$@' == '' ]; then
    exec su-exec ${UID}:${GID} /sbin/tini -- /usr/local/go/bin/go version
else
    exec su-exec ${UID}:${GID} /sbin/tini -- /usr/local/go/bin/go "$@"
fi

