#!/bin/sh

addgroup -g ${GID} ${USER} && adduser -h /home/${USER} -s /bin/sh -D -G ${USER} -u ${UID} ${USER}

mkdir -p /home/${USER}
mkdir -p /etc/dropbear/

chown -R ${USER}:${USER} /${USER}

dropbear -RFEmwg -p 22
