#!/bin/bash

grep lufi /etc/group > /dev/null 2>&1; [[ $? -eq 1 ]] && addgroup --gid ${GID} lufi
grep lufi /etc/passwd > /dev/null 2>&1; [[ $? -eq 1 ]] && adduser --system --shell /bin/sh --no-create-home --ingroup lufi --uid ${UID} lufi

chown -R lufi:lufi /data /lufi /files

sed -i -e 's|<secret>|'${SECRET}'|' \
        -e 's|<contact>|'${CONTACT}'|' \
        -e 's|<max_file_size>|'${MAX_FILE_SIZE}'|' \
        -e 's|<webroot>|'${WEBROOT}'|' /lufi/lufi.conf

cd /lufi
exec su-exec lufi:lufi tini -- /usr/local/bin/carton exec hypnotoad -f /lufi/script/lufi
