#!/bin/bash

grep lutim /etc/group > /dev/null 2>&1; [[ $? -eq 1 ]] && addgroup --gid ${GID} lutim
grep lutim /etc/passwd > /dev/null 2>&1; [[ $? -eq 1 ]] && adduser --system --shell /bin/sh --no-create-home --ingroup lutim --uid ${UID} lutim

chown -R lutim:lutim /data /lutim /files

sed -i -e 's|<secret>|'${SECRET}'|' \
        -e 's|<contact>|'${CONTACT}'|' \
        -e 's|<max_file_size>|'${MAX_FILE_SIZE}'|' \
        -e 's|<webroot>|'${WEBROOT}'|' /lutim/lutim.conf

cd /lutim
su lutim -c "/usr/local/bin/carton exec hypnotoad -f /lutim/script/lutim"

