#!/bin/sh

if ! test -f /etc/sshd/ssh_host_rsa_key; then
    ssh-keygen -q -f /etc/sshd/ssh_host_rsa_key -N '' -t rsa
fi

if ! test -f /etc/sshd/ssh_host_dsa_key; then
    ssh-keygen -q -f /etc/sshd/ssh_host_dsa_key -N '' -t dsa
fi

if ! test -f /etc/sshd/ssh_host_ecdsa_key; then
    ssh-keygen -q -f /etc/sshd/ssh_host_ecdsa_key -N '' -t ecdsa
fi

if ! test -f /etc/sshd/ssh_host_ed25519_key; then
    ssh-keygen -q -f /etc/sshd/ssh_host_ed25519_key -N '' -t ed25519
fi

chmod 0700 /etc/sshd
chmod 0600 /etc/sshd/*