#!/bin/sh

addgroup -g ${GID} 0bin && adduser -h /home/0bin -s /bin/sh -D -G 0bin -u ${UID} 0bin

if [ ! -z ${CUSTOM_MENU_NAME} ] && [ ! -z ${CUSTOM_MENU_LINK} ]; then
        sed -i "s%#<custom menu>%('${CUSTOM_MENU_NAME}', '${CUSTOM_MENU_LINK}'),%" /zerobin/settings.py
        sleep 2
fi

sed -i 's/<email>/'$CONTACT_MAIL'/' /zerobin/settings.py

chown -R 0bin:0bin /paste

su - 0bin -c "zerobin --settings-file=/zerobin/settings.py"
