#!/bin/sh

if [ ! -f /config/config.ini ]
then
	if [ -z ${APIKEY} ]; then
		APIKEY=$(date +%s | md5sum | head -c 32)
	fi
	mv /tmp/config.ini /config/config.ini
	sed -i "s|<webroot>|"${WEBROOT}"|" /config/config.ini
	sed -i "s|<apikey>|"${APIKEY}"|" /config/config.ini
fi

mkdir -p /config/data
chown -R ${UID}:${GID} /config
chown -R ${UID}:${GID} /CouchPotatoServer

gosu ${UID}:${GID} sh -c "cd /CouchPotatoServer && /usr/bin/python /CouchPotatoServer/CouchPotato.py --config_file=/config/config.ini --data_dir=/config/data"
