#!/bin/sh

addgroup -g ${GID} couchpotato && adduser -h /home/couchpotato -s /bin/sh -D -G couchpotato -u ${UID} couchpotato

if [ ! -f /config/config.ini ]
then
	if [ -z ${APIKEY} ]; then
		APIKEY=$(date +%s | md5sum | head -c 32)
	fi
	mv /tmp/config.ini /config/config.ini
	sed -i "s|<webroot>|"${WEBROOT}"|" /config/config.ini
	sed -i "s|<apikey>|"${APIKEY}"|" /config/config.ini
fi

mkdir -p /config/data
chown -R couchpotato:couchpotato /config
chown -R couchpotato:couchpotato /CouchPotatoServer

supervisord
