#!/bin/sh

if [ ! -e /Up1/server.conf ]
then
        if [ -z ${APIKEY} ]
        then
                APIKEY=$(date +%s | md5sum | head -c 32)
        	echo "api_key : ${APIKEY}"
	fi
        sleep 2
        if [ -z ${DELETEKEY} ]
        then
                DELETEKEY=$(date +%s | md5sum | head -c 32)
        	echo "delete_key : ${DELETEKEY}"
	fi


cat > /Up1/config.js << EOF
upload.config.server = ''
upload.config.api_key = '${APIKEY}'
upload.config.contact_link = 'mailto:someemail@email'
EOF

cat > /Up1/server.conf << EOF
{
  "api_key": "${APIKEY}",
  "delete_key": "${DELETEKEY}",
  "maximum_file_size": 50000000,
  "webroot": "",

  "http": {
    "enabled": true,
    "listen": ":5000"
  },

  "https": {
    "enabled": false,
    "listen": ":5443",
    "cert": "./cert.pem",
    "key": "./key.pem"
  },

  "cloudflare-cache-invalidate": {
    "enabled": false,
    "token": "Cloudflare API token here",
    "email": "Cloudflare login email here",
    "domain": "Domain to invalidate cache on"
  }
}
EOF


fi

# addgroup -g ${GID} up1 && adduser -D -h /Up1 -s /bin/sh -u ${UID} -G up1 up1
chown -R ${UID}:${GID} /Up1

gosu ${UID}:${GID} -c "/usr/bin/up1"
