#!/bin/sh

export HOME="/home/${USER}"
export DISPLAY=":1"
export USER="${USER}"

while [ true ]; do
    if [ "$(ps -ef | grep x11vnc | grep -v grep)" != "" ]; then break; fi
done

exec /usr/bin/openbox