#!/bin/sh

addgroup -g ${GID} jackett && adduser -h /home/jackett -s /bin/sh -G jackett -u ${UID} -D jackett

chown -R ${UID}:${GID} /opt/Jackett
chown -R ${UID}:${GID} /home/jackett

gosu ${UID}:${GID} sh -c "cd /opt/Jackett && mono JackettConsole.exe"
