#!/bin/sh

addgroup -g ${GID} sickrage && adduser -h /home/sickrage -s /bin/sh -D -G sickrage -u ${UID} sickrage

if [ ! -f /config/config.ini ]
then
	mv /tmp/config.ini /config/config.ini
	sed -i "s|<webroot>|"${WEBROOT}"|" /config/config.ini
fi

chown -R sickrage:sickrage /config
chown -R sickrage:sickrage /SickRage

supervisord
