#!/bin/sh

sed -i 's/<rtorrent_host>/'${RTORRENT_HOST}'/;s/<rtorrent_port>/'${RTORRENT_PORT}'/;s/<rtorrent_socket>/'${RTORRENT_SOCKET}'/;s|<rtorrent_socket_path>|'${RTORRENT_SOCKET_PATH}'|;s/<flood_secret>/'${FLOOD_SECRET}'/' /usr/app/src/config.js

chown -R ${UID}:${GID} /usr/app/src

su-exec ${UID}:${GID} ./node_modules/.bin/gulp dist

if [ "${FLOOD_START}" == "develop" ]; then
    su-exec ${UID}:${GID} ./node_modules/.bin/nodemon ./server/bin/www
elif [ "${FLOOD_START}" == "watch" ]; then
    su-exec ${UID}:${GID} ./node_modules/.bin/nodemon ./server/bin/www &
    su-exec ${UID}:${GID} NODE_ENV='development' ./node_modules/.bin/gulp livereload
else
    su-exec ${UID}:${GID} node ./server/bin/www
fi

