#!/bin/bash

if [ -z $1 ]
then
    echo "Empty container name"
    exit 1
fi


INFO=$(/usr/bin/docker ps -a --format "{{.Names}}|{{.Status}}" -f "Name=$1")
if [ "$INFO" == "" ];then
    echo "Container not found"
    exit 1
else
    STATUS=$(echo $INFO | cut -d"|" -f2)
    if [[ $STATUS != Up* ]]; then
        echo ${STATUS} 
        exit 2
    else
        echo ${STATUS}
        echo -e "\nStats :"
        /usr/bin/docker stats --no-stream $1
        echo -e "\nTop :"
        /usr/bin/docker top $1
        exit 0
    fi
fi
