#!/bin/sh

addgroup -g ${GID} gulp 2> /dev/null
adduser -h /home/gulp -D -s /bin/sh -D -G gulp gulp

if [ -e gulpfile.js ]; then
	npm install --save-dev
else
	npm install gulp --save-dev
fi

su - gulp -c "gulp $@"
