#!/bin/bash
set -e

PKG_BUILD="build-base wget autoconf"
apk add --update ${PKG_BUILD}

if [ ! -e /tmp/php-${PHP_VER}.tar.gz ]
then
        cd /tmp
        wget --no-check-certificate https://downloads.php.net/~ab/php-${PHP_VER}.tar.gz
        tar -xzf php-${PHP_VER}.tar.gz -C /usr/src/ && mv /usr/src/php-${PHP_VER} /usr/src/php
else
        if [ ! -d /usr/src/php ]
        then
                cd /tmp
                tar -xzf php-${PHP_VER}.tar.gz -C /usr/src/ && mv /usr/src/php-${PHP_VER} /usr/src/php
        fi
fi

ext="$1"
extDir="/usr/src/php/ext/$ext"
if [ -z "$ext" -o ! -d "$extDir" ]; then
	echo >&2 "usage: $0 ext-name [configure flags]"
	echo >&2 "   ie: $0 gd --with-jpeg-dir=/usr/local/something"
	echo >&2
	echo >&2 'Possible values for ext-name:'
	echo >&2 $(find /usr/src/php/ext -mindepth 2 -maxdepth 2 -type f -name 'config.m4' | cut -d/ -f6 | sort)
	apk del ${PKG_BUILD} && rm -rf /var/cache/apk/* /tmp/* /usr/src/php /tmp/*
	exit 1
fi
shift

set -x
cd "$extDir"
phpize
./configure "$@"
