#!/bin/sh

deluser transmission
addgroup -g ${GID} transmission && adduser -h /home/transmission -D -G transmission -s /bin/sh -u ${UID} transmission

if [ ! -f /home/transmission/.config/transmission-daemon/settings.json ]
then
    mkdir -p /home/transmission/.config/transmission-daemon/
    mv /tmp/settings.json /home/transmission/.config/transmission-daemon/settings.json
    sed -i "s|<webroot>|"${WEBROOT}"|" /home/transmission/.config/transmission-daemon/settings.json
fi

mkdir -p /data/torrents /data/Media /data/watch
chown -R transmission:transmission /data /home/transmission

exec su-exec transmission:transmission tini -- transmission-daemon --foreground
